AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/**
  SuggestExtensions: false
Style/RedundantReturn:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 60
Metrics/ClassLength:
  Max: 410
Metrics/BlockLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Max: 14
Style/FormatStringToken:
  Enabled: false
Style/FormatString:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Style/CaseLikeIf:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/WordArray:
  Enabled: false
